meta_product_name: "Seamify"
meta_title: "Seamify - Alterations and repairs made for you."
meta_description: "An application for alterations and repairs for the people."
meta_image: "seamify-logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account" # required for Twitter Cards
